- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
      - debug:
          msg: {{ec2_access_key}}

      - debug:
          msg: {{ec2_access_key}}

      - name: create a security group in us-east-1
        ec2_group:
          name: dmz
          description: an example ec2 group
          region: 
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
        register: security_group


---
- hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    ami: "<insert AMI value here>"
    region: "us-east-1"
    type: "t2.micro"
    sshkey: "<insert keypair name>"
    vpcid: "<insert VPC ID>"

  tasks:
  - name: "Create a new security group"
    ec2_group:
      name: "ansible-sec-group"
      description: "New SG for Ansible-created instances"
      region: "{{ region }}"
      vpc_id: "{{ vpcid }}"
      rules:
        - proto: "tcp"
          from_port: 22
          to_port: 22
          cidr_ip: "0.0.0.0/0"
      rules_egress:
        - proto: "all"
          cidr_ip: "0.0.0.0/0"
    register: secgrp

  - name: "Provision an EC2 instance"
    ec2:
      key_name: "{{ sshkey }}"
      group_id: "{{ secgrp.group_id }}"
      instance_type: "{{ type }}"
      ec2_region: "{{ region }}"
      image: "{{ ami }}"
      wait: true
      count: 1
      instance_tags:
        tool: "ansible"
        env: "test"
    register: ec2instance



  
